version: "3.9"
services:
  web:
    container_name: nginx
    image: nginx-1.22-alpine-app:0.1
    build: build
    stdin_open: true
    ports:
      - 9889:80
    volumes:
      - 'web_templates:/etc/nginx/templates'
    environment:
      - SERVER_NAME=web
      - PORT=80
    networks:
      nginxnet:
        ipv4_address: 172.18.0.2

networks:
  nginxnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  web_templates:
    driver: local
    driver_opts:
      type: 'volume'
      o: 'bind'
      device: './templates'
